"""Initial catalog (Phase 0). IDs must be validated against each source API: run `python -m kondratiev.validate`."""
CATALOG = [
    dict(id="fred_dgs10", perspective="kondratiev", layer="timing", source="fred", code="DGS10",
         name="Juros do Tesouro EUA 10 anos", country="USA", unit="% a.a.", frequency="daily", role="procyclical",
         rationale="Juros longos sobem na expansão (fase A) e são o preço de referência do capital no ciclo de Kondratiev.",
         source_url="https://fred.stlouisfed.org/series/DGS10", stale_after_days=7),
    dict(id="fred_cpiaucsl", perspective="kondratiev", layer="regime", source="fred", code="CPIAUCSL",
         name="Índice de preços ao consumidor (EUA)", country="USA", unit="índice 1982-84=100", frequency="monthly",
         role="procyclical",
         rationale="Preços acelerando caracterizam a fase A; deflação ou desinflação prolongada, a fase B.",
         source_url="https://fred.stlouisfed.org/series/CPIAUCSL", stale_after_days=60),

    # World Bank (keyless, annual: structure layer, 1-2 year publication lag)
    dict(id="wb_wld_fp_cpi_totl_zg", perspective="kondratiev", layer="structure", source="worldbank", code="FP.CPI.TOTL.ZG",
         name="Inflação ao consumidor (Mundo)", country="WLD", unit="% a.a.", frequency="annual", role="procyclical",
         rationale="Preços acelerando caracterizam a fase A; desinflação prolongada, a fase B.",
         source_url="https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG?locations=1W", stale_after_days=900),
    dict(id="wb_wld_ny_gdp_defl_kd_zg", perspective="kondratiev", layer="structure", source="worldbank", code="NY.GDP.DEFL.KD.ZG",
         name="Deflator do PIB (Mundo)", country="WLD", unit="% a.a.", frequency="annual", role="procyclical",
         rationale="Medida ampla de preços: sobe na expansão, cai na contração longa.",
         source_url="https://data.worldbank.org/indicator/NY.GDP.DEFL.KD.ZG?locations=1W", stale_after_days=900),
    dict(id="wb_wld_ny_gdp_mktp_kd_zg", perspective="kondratiev", layer="structure", source="worldbank", code="NY.GDP.MKTP.KD.ZG",
         name="Crescimento do PIB (Mundo)", country="WLD", unit="% a.a.", frequency="annual", role="procyclical",
         rationale="Ritmo de produção: mais forte na fase A do ciclo longo.",
         source_url="https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG?locations=1W", stale_after_days=900),
    dict(id="wb_wld_gb_xpd_rsdv_gd_zs", perspective="schumpeter", layer="structure", source="worldbank", code="GB.XPD.RSDV.GD.ZS",
         name="P&D como % do PIB", country="WLD", unit="% do PIB", frequency="annual", role="procyclical",
         rationale="Esforço de inovação: base de novos clusters tecnológicos.",
         source_url="https://data.worldbank.org/indicator/GB.XPD.RSDV.GD.ZS?locations=1W", stale_after_days=900),
    dict(id="wb_wld_ip_pat_resd", perspective="schumpeter", layer="structure", source="worldbank", code="IP.PAT.RESD",
         name="Patentes depositadas (residentes)", country="WLD", unit="patentes", frequency="annual", role="procyclical",
         rationale="Fluxo de invenções, que antecede a onda de inovações.",
         source_url="https://data.worldbank.org/indicator/IP.PAT.RESD?locations=1W", stale_after_days=900),
    dict(id="wb_wld_sp_pop_scie_rd_p6", perspective="schumpeter", layer="structure", source="worldbank", code="SP.POP.SCIE.RD.P6",
         name="Pesquisadores por milhão de habitantes", country="WLD", unit="por milhão", frequency="annual", role="procyclical",
         rationale="Capacidade humana de inovar.",
         source_url="https://data.worldbank.org/indicator/SP.POP.SCIE.RD.P6?locations=1W", stale_after_days=900),
    dict(id="wb_wld_tx_val_tech_mf_zs", perspective="schumpeter", layer="structure", source="worldbank", code="TX.VAL.TECH.MF.ZS",
         name="Exportações de alta tecnologia", country="WLD", unit="% das exportações industriais", frequency="annual", role="procyclical",
         rationale="Difusão comercial das tecnologias novas.",
         source_url="https://data.worldbank.org/indicator/TX.VAL.TECH.MF.ZS?locations=1W", stale_after_days=900),
    dict(id="wb_wld_cm_mkt_lcap_gd_zs", perspective="perez", layer="structure", source="worldbank", code="CM.MKT.LCAP.GD.ZS",
         name="Capitalização de mercado das ações", country="WLD", unit="% do PIB", frequency="annual", role="procyclical",
         rationale="Indicador Buffett: capital financeiro descolado do produtivo sinaliza frenesi.",
         source_url="https://data.worldbank.org/indicator/CM.MKT.LCAP.GD.ZS?locations=1W", stale_after_days=900),
    dict(id="wb_wld_cm_mkt_trad_gd_zs", perspective="perez", layer="structure", source="worldbank", code="CM.MKT.TRAD.GD.ZS",
         name="Valor das ações negociadas", country="WLD", unit="% do PIB", frequency="annual", role="procyclical",
         rationale="Intensidade especulativa do mercado.",
         source_url="https://data.worldbank.org/indicator/CM.MKT.TRAD.GD.ZS?locations=1W", stale_after_days=900),
    dict(id="wb_wld_tx_val_ictg_zs_un", perspective="perez", layer="structure", source="worldbank", code="TX.VAL.ICTG.ZS.UN",
         name="Exportações de TIC", country="WLD", unit="% das exportações de bens", frequency="annual", role="procyclical",
         rationale="Peso do paradigma tecnológico atual (informação).",
         source_url="https://data.worldbank.org/indicator/TX.VAL.ICTG.ZS.UN?locations=1W", stale_after_days=900),
    dict(id="wb_wld_eg_fec_rnew_zs", perspective="freeman", layer="structure", source="worldbank", code="EG.FEC.RNEW.ZS",
         name="Energia renovável no consumo final", country="WLD", unit="% do consumo", frequency="annual", role="procyclical",
         rationale="Difusão do novo insumo-chave energético.",
         source_url="https://data.worldbank.org/indicator/EG.FEC.RNEW.ZS?locations=1W", stale_after_days=900),
    dict(id="wb_wld_en_ghg_co2_pc_ce_ar5", perspective="freeman", layer="structure", source="worldbank", code="EN.GHG.CO2.PC.CE.AR5",
         name="Emissões de CO₂ per capita", country="WLD", unit="t por pessoa", frequency="annual", role="procyclical",
         rationale="Queda sinaliza descarbonização da base produtiva.",
         source_url="https://data.worldbank.org/indicator/EN.GHG.CO2.PC.CE.AR5?locations=1W", stale_after_days=900),
    dict(id="wb_wld_eg_egy_prim_pp_kd", perspective="freeman", layer="structure", source="worldbank", code="EG.EGY.PRIM.PP.KD",
         name="Intensidade energética do PIB", country="WLD", unit="MJ por US$ de PIB", frequency="annual", role="procyclical",
         rationale="Queda sinaliza eficiência do paradigma vigente.",
         source_url="https://data.worldbank.org/indicator/EG.EGY.PRIM.PP.KD?locations=1W", stale_after_days=900),
    dict(id="wb_wld_fs_ast_prvt_gd_zs", perspective="minsky", layer="structure", source="worldbank", code="FS.AST.PRVT.GD.ZS",
         name="Crédito ao setor privado", country="WLD", unit="% do PIB", frequency="annual", role="procyclical",
         rationale="Alavancagem do setor privado: excesso gera fragilidade.",
         source_url="https://data.worldbank.org/indicator/FS.AST.PRVT.GD.ZS?locations=1W", stale_after_days=900),
    # US Treasury (keyless, daily)
    dict(id="ust_10y", perspective="kondratiev", layer="timing", source="treasury", code="10 Yr",
         name="Juros do Tesouro EUA 10 anos", country="USA", unit="% a.a.", frequency="daily", role="procyclical",
         rationale="Juros longos sobem na expansão (fase A) e são o preço de referência do capital.",
         source_url="https://home.treasury.gov/resource-center/data-chart-center/interest-rates", stale_after_days=7),
    dict(id="ust_2y", perspective="minsky", layer="timing", source="treasury", code="2 Yr",
         name="Juros do Tesouro EUA 2 anos", country="USA", unit="% a.a.", frequency="daily", role="fragility",
         rationale="Com o de 10 anos forma a curva de juros; inversão (2 anos acima de 10) antecede crises.",
         source_url="https://home.treasury.gov/resource-center/data-chart-center/interest-rates", stale_after_days=7),
]
